# Generated by Django 3.0.8 on 2020-10-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='endTime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='startTime',
            field=models.TimeField(null=True),
        ),
    ]
