# Generated by Django 3.0.8 on 2020-10-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201009_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='endTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='startTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='ticketPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='totalTickets',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
